### PR TITLE
Fix remove attribute

### PR DESCRIPTION
**Pull request by pahanium**
Fix plugin deinstall bug

### CODE REVIEW

**Comment by mitelg** [comment]
hey @pahanium 
thanks for your contribution. Did you test your changes with Shopware 4.2? As you can see [here](https://github.com/shopwareLabs/SwagPaymentPaypalPlus/blob/master/plugin.json#L69) this plugin is compatible down until this version :wink:

**Comment by pahanium** [comment]
PayPal PLUS not support 5.5 and method "removeAttribute" was removed in 5.5.
Sorry, but the problem to deinstall in shopware greater than 5.5 due to an error.
You can delete pull request or check my updated code )

**Comment by mitelg** [comment]
hey @pahanium 
We are not planning to make this plugin compatible with Shopware 5.5. If you want to use PayPal Plus you can use this plugin -> 
Github: https://github.com/shopwareLabs/SwagPaymentPayPalUnified 
Store: https://store.shopware.com/swag828732772311f/paypal.html 
Docs: https://en-community.shopware.com/_detail_2078.html

With your changes you will break installations lower Shopware 5.2.2
The attributes will not removed anymore. Please make sure that the plugin works from Shopware 4.2.0 until 5.4.7. 
Maybe our new plugin fixes your problem, too. If so, we would like to close your PR

**Comment by mitelg** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request. 

For more information about our contribution guidelines, see https://developers.shopware.com/contributing/contribution-guideline/.

**Pull request closed without merging**
